apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hub-project
  namespace: my-hub-project
  labels:
    app: my-hub-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-hub-project
  template:
    metadata:
      labels:
        app: my-hub-project
    spec:
      containers:
        - name: my-app-container 
          image: sreeju1909/rio:latest
          ports:
            - containerPort: 8080
