apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment
  namespace: my-hub-project
spec:
  selector:
    app: my-hub-project  # Correctly indented under 'selector'
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080          # The external port exposed by the LoadBalancer
      targetPort: 8080    # The port on the container

